### ISSUE TITLE
Layers API?

### ISSUE THREAD

**Issue by eried** [antipole2/JavaScripts-shared#1]
Hi, is there is a way to update/create Layers (or manually update waypoints and tracks from a gpx file?) i.e. every 15 mins

**Comment by antipole2** [comment]
Not sure what you are wanting to achieve?  Why do you want to regularly update from a .gox file?
As far as I know, OCPN APIs has no support for touching layers.

**Comment by eried** [comment]
Hi, there is some markers in the map that change (fishing gear) and I am looking for a way to update these markers every X minutes (trying to avoid to have to write a plugin from scratch)

**Comment by antipole2** [comment]
Still not clear to me...  where do the changes occur?  In the OCPN map?  Please explain further.

**Comment by eried** [comment]
There is a website that posts a new GPX file with fishing gear, I load here:
![image](https://user-images.githubusercontent.com/1091420/195538164-8dfcc807-10e6-4b76-8bcc-2b1ba70cf6bb.png)

It loads several things:
![image](https://user-images.githubusercontent.com/1091420/195538329-742dc2bd-e90b-48cd-810b-45e106ac8688.png)

They work ok, they are displayed, but I want the next GPX file to update that layer, or refresh that file, or the objects. I am not sure what would be easier

**Comment by antipole2** [comment]
There is no way a plugin can update a layer permanently.  I have discovered that it can update a layer but the changes will be lost when OCPN quits.
Is all your data replaced with the new gpx file or does it just contain updates?
One option might be to not use a layer but have them as ordinary waypoints/routes etc.
You could create a JavaScript to read a gpx file and create/update the objects.  I do not have any samples code for decoding  gpx in JavaScript but there is code on the internet.  It is realistic but not a 10 minute job to get it working.
One issue you would need to resolve is how do you match an update with existing objects in OpenCPN.  Are the names unique?  In OpenCPN objects are identified by their unique GUID.  But unless your gpx data has come fromOpenCPN, it will not have any GUID you can use to match with an existing object.

**Comment by eried** [comment]
I see... the new gpx includes all new objects so I need to rethink the problem. Maybe some intermediate format, but the unique naming will be a problem... Thanks for the info

**Comment by antipole2** [comment]
@eried Can you close this now?
